In [1]:
import numpy as np

In [2]:
a = np.array([2, 1])

In [3]:
print(a)

[2 1]


In [4]:
type(a)

numpy.ndarray

In [10]:
d = np.array([[1], [5]])

In [11]:
print(d)

[[1]
 [5]]


In [12]:
type(d)

numpy.ndarray

In [13]:
print(d.T)

[[1 5]]


In [14]:
print(d.T.T)

[[1]
 [5]]


In [17]:
a = np.array([1, 2])
b = np.array([2, 5])

In [18]:
a + b

array([3, 7])